### ISSUE TITLE
AttributeError: IMG_SIZE

### ISSUE THREAD

**Issue by peter-ch** [zhengxiawu/XNAS#14]
I get this error trying to run the code like "python scripts/search/DARTS.py --cfg configs/search/darts_darts_cifar10.yaml" :

Traceback (most recent call last):
  File "scripts/search/DARTS.py", line 70, in <module>
    main()
  File "scripts/search/DARTS.py", line 24, in main
    [train_loader, valid_loader] = construct_loader()
  File "C:\Users\spook\Dropbox\Desktop\NAS\XNAS\newenv\lib\site-packages\xnas\datasets\loader.py", line 47, in construct_loader
    if isinstance(cfg.SEARCH.IMG_SIZE, list):
  File "C:\Users\spook\Dropbox\Desktop\NAS\XNAS\newenv\lib\site-packages\yacs\config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: IMG_SIZE

**Comment by xfey** [comment]
Hi👋, thanks for using our code. This bug has been fixed now, please pull the latest code and re-run it.
